server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.139.135
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.139.135
ly:
  sms:
    accessKeyId: LTAI4GKP99pY5j8Fjqq2iyGP # 你自己的accessKeyId
    accessKeySecret: 578aDGEQH9e12XAp2DMJRaFSEE3iv6 # 你自己的AccessKeySecret
    signName: candy # 签名名称
    verifyCodeTemplate: SMS_166376606 # 模板名称